org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Build specific
minecraft_version   = 1.21.5
loader_version      = 0.16.9

# Mod properties
mod_version         = 1.2.2
maven_group         = io.github.projectet.buildinggadgets-fabric
archives_base_name  = structure-tools-continued

# Dependencies
fabric_api_version  = 0.128.2+1.21.5
energy_version      = 4.2.0
cloth_config_version= 18.0.145
modmenu_version     = 14.0.2
architectury_version= 16.1.4
rei_version         = 19.0.809
cca_version         = 6.3.1
parchment_version   = 2025.06.15
goml_version        = 1.16.0+1.21.5
rtree_version       = 0.3.0
flan_version        = 1.11.15
pal_version         = 1.13.0