org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Build specific
minecraft_version   = 1.20.4
loader_version=0.18.4

# Mod properties
mod_version         = 1.1.0
maven_group         = io.github.projectet.buildinggadgets-fabric
archives_base_name  = structure-tools-continued

# Dependencies
fabric_api_version  = 0.97.3+1.20.4
energy_version      = 3.0.0
cloth_config_version= 13.0.138
modmenu_version     = 9.2.0
architectury_version= 9.2.14
rei_version         = 14.1.786
cca_version         = 5.4.0
parchment_version   = 2024.04.14
goml_version        = 1.9.4
rtree_version       = 0.3.0
flan_version        = 1.11.15
ipn_version         = 4.0.2
pal_version         = 1.9.0

ftblibrary_version  = 2001.2.12
ftbteams_version    = 2001.3.1
ftbchunks_version   = 2001.3.6
