org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Build specific
minecraft_version   = 26.1.2
loader_version      = 0.19.0

# Mod properties
mod_version         = 1.2.2
maven_group         = io.github.projectet.buildinggadgets-fabric
archives_base_name  = structure-tools-continued

# Dependencies
fabric_api_version  = 0.145.4+26.1.2
energy_version      = 5.0.0
cloth_config_version= 26.1.154
modmenu_version     = 18.0.0-alpha.8
cca_version         = 8.0.0
rtree_version       = 0.3.0
flan_version        = 1.11.15
pal_version         = 1.16.0
